### ISSUE TITLE
high tea 

### ISSUE THREAD

**Issue by pedroklooster** [jappeace/offertex#10]
Als ik een offerte maak met high tea de huiskamer dan breekt hij op het laatste af en lukt de offerte niet.
Ik doe dan high tea ansen die werkt wel en vul de details en prijzen dan verder aan

Bij consumptie's komt ook kinderen te staan terwijl die gewoon de zelfde prijs wordt

Groetjes Pedro

**Comment by jappeace** [comment]
Deze was ook al klaar
