### ISSUE TITLE
aanpassing

### ISSUE THREAD

**Issue by pedroklooster** [jappeace/offertex#2]
had gisteren een offerte en die wilde een buffet uitbreiden.
Nog een open veld eigen tekst dan invoeren en een eigen zelf een bedrag invoeren.

Hapjes buffet van de site staat niet bij het eten mag nu een offerte maken maar kom dus niet verder.

**Comment by jappeace** [comment]
Na bespreking blijkt dat word bedoelt dat bij buffetten extra gerechten moeten kunnen worden toegevoegd. Dus bijvoorbeeld:
- Rijstafel
  - Extra bacon 1 euro
  - Extra rijst 3 euro

Het bedrag pp zelf invullen netzo als de text.

**Comment by jappeace** [comment]
Naar verdere bespreking moet er gewoon een invulsel komen in het menu die het prijs overzicht aanpast, maar in het draaiboek weg word gelaten (dus met tijd 0?).

**Comment by jappeace** [comment]
Dit kan nu handmatig worden ingevult, of eigen details invoeren, of je kan nieuwe tijdelijke activteiten maken.
