### ISSUE TITLE
ter attentie van en open veld bij de nota

### ISSUE THREAD

**Issue by pedroklooster** [jappeace/offertex#3]
Jappie bij de adres gegevens zou nog een veld moeten t.a.v. 
(ter attentie van) dit wordt bij grote bedrijven en gemeente veel gebruikt
dus dan bijvoorbeeld zo
Restaurant de Huiskamer
t.a.v. Pedro Klooster
Kerkdijk 2
7965 KB  Ansen

En bij de kosten berekening zou van mij ook nog wel een openveld mogen waar ik zelf een tekst en een bedrag ik kan voeren.  Soms willen de gasten iets buiten het standaard om bijvoorbeeld extra vis bij een buffet Ansen. Dan zou ik dus een veld krijgen bij de kosten berekening met de vraag bijonderheid en dan typ ik extra vis. En dan de vraag prijs p.p. bijvoorbeeld 5,00 en dan berekend hij dit van het aantal personen wat al was opgegeven.  

Dit hoeft dan niet in het draaiboek verwerkt te worden. Kan het dan eventeel altijd nog bij de opmerkingen plaatsen.

O ja kun je bij Dieet er ook van maken Dieet / Allergie

Groetjes Pedro Klooster

**Comment by jappeace** [comment]
Je kan nu eigen tijdelijke activiteiten toevoegen. Je kan nu prijzen pp, tijd, en aantal gasten bewerken, daarnaast eigen details toevoegen. Tex bestanden kun jezelf aanpassen
