### ISSUE TITLE
kinderen nul bedrag nummering klopt niet

### ISSUE THREAD

**Issue by pedroklooster** [jappeace/offertex#7]
Bij de kinderen geeft ie een nul bedrag aan maar plaats hij bv ook bij koffie met gebak korting eronder nul bedrag terwijl dit niet zo is.  
Bij de keuze klopt van nummers klopt ook niet wat je in toest bv 
koffie met gebak wordt dan koffie met cake

**Comment by jappeace** [comment]
Ik het "nummer" gedeelte niet herproduceren, geef aub een preciese invoer. Of, nog beter kopieer de terminal output in de issue inclusief de latex output.

Kinder prijs korting in de laatste versie gefixed (zie commit).
